apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "dbaas.redhat.com/v1alpha1",
          "kind": "CrdbDBaaSConnection",
          "metadata": {
            "name": "crdbdbaasconnection-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "dbaas.redhat.com/v1alpha1",
          "kind": "CrdbDBaaSInventory",
          "metadata": {
            "name": "crdbdbaasinventory-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    categories: Database
    containerImage: quay.io/<cockroach>/ccapi-k8s-operator:v0.0.1
    createdAt: <CREATED_AT_PLACEHOLDER>
    operators.operatorframework.io/builder: operator-sdk-v1.15.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/cockroachdb/ccapi-k8s-operator
    support: Cockroach Labs
  name: ccapi-k8s-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CrdbDBaaSConnection is the Schema for the crdbdbaasconnections
        API
      displayName: Crdb DBaaS Connection
      kind: CrdbDBaaSConnection
      name: crdbdbaasconnections.dbaas.redhat.com
      version: v1alpha1
    - description: CrdbDBaaSInventory is the Schema for the crdbdbaasinventories API
      displayName: Crdb DBaaS Inventory
      kind: CrdbDBaaSInventory
      name: crdbdbaasinventories.dbaas.redhat.com
      version: v1alpha1
  description: CockroachDB Cloud Operator
  displayName: CockroachDB Cloud Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA/xJREFUeNq0V9uLE1cY/85k08wk2TWyf8AGH30oI8kigrLxgsULbqC1PrR0Z3rRQh928yD2ySUKgvhg9lFFZ1ZhZR+kkdaCgiUrBSm7YYc+9KmF2AfBBzF46V6SOcfvTM7kvu5kM/1gcgIz53y/7/fdzkegSQK77y4roKhhJkMEFAgzfPgKcjnCFAv/LyhMzt8pRizoIkezq2o1wtKVQTpWGWRqJcpiuML6IAW+8qcaZda/Q8O73D0DrUeQEv6o7QcTgBguKf4QINNnkrZFw2TmxhPJ5O9PnlnXUNlkhTIVNhMGpbazGxLcPR+v/HGq1L5n/+jfqsKQGZDHkZW0QmSwIwCotFDZRvmaciyMOk8eGbiPq/X7l9EOpkbKL+PPYsOlrgC8yNeJtVhQCk7ZYZh2aUWFgNRnqwrL/XxJLvdyntQrgFvFEFcw0uXVSK/KtwRgIrFioB81hz4KGSAs47hWAu3Y+VXjfwXwefLVFANWU26Dbv4ayM3NBXOoXBcO1T65vDLVy5meY+B48rkqQ2iZp6YMH2WuFwdyze/Hz65OVcNw1Uk1he367Yew5SsDFJhRyyJWaFfO5f4VmTNRcL4JMMNXFxxI/oO013KcEjqzYYpLbEbwqu67/VbzDQAlbLJRR1j5Aw61GmBg0hcAe0b/Ul3rPUi86WR1z703at8A0OJ0S79ggQ0tIzaZbHUJpPsGgME3VgMCZo1lkj6dqHb4d/zsmoZ1wVVoCgBjfjDAmxDYYGclIE70EyIZ3+2ldRCffb/OlRuiPuToAGRFTKQ2O3/Aa7o8WhrhDSSDlZB3Ro0FwNCO2LA2jH2AirRjYD48pziVce/c2/7T8OPRYkrQX+9es0VFR8tqFCMI9LshyrL54IKsN5ir7Uk8ep3qOw3RDS0t+tqipDenHCov/HQ1pLelZMmPNCyLwOtIJxpg2QYA0lGcCKtfbMpbBvDnYsJquhG1tuXHgbz7f/5WMN9lu7OneHjI6tcFjgWHk8+8FiMYu/nOk/WeAGDqFYQbUl4BYNCkRBEp9A0AFS8IIBOeezyFCREHC34AyLuBmE6+iG/2/aGZ/+JuACKQfN8Ani7uLKFys/axNL0pYBumxWo+/XSw1DcA5yMmzQoA2hfJNxvGwpGLKylMSU3QP+vbfeDx0o5CnQUmGd8mKh1peeLcaqxeFdH6J19FC74BENbzGl9GIHEJm1GXVmyg1XHMgDKykPH9UsrlVPKVGmKhZT4ZUQXM9W1Mc2a/IWrizMfHM+dC+vBHxfJuWA8yv7TdQiZ0dw5oKrvunKD3onxLg4lZlE1CiN5S5TjtOCf8clE2ez2v59nQlW8O2mo1zIwqDqm46tgPrK2c816AAQCBW4SEJD8W2QAAAABJRU5ErkJggg==
    mediatype: image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasconnections
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasconnections/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasconnections/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasinventories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasinventories/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - crdbdbaasinventories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ccapi-k8s-operator-controller-manager
      deployments:
      - name: ccapi-k8s-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: INSTALL_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/myeung/ccapi-k8s-operator:0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ccapi-k8s-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ccapi-k8s-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cockroachDB Cloud
  - database
  links:
  - name: CockroachDB Cloud
    url: https://cockroachlabs.cloud
  - name: Cockroach Labs
    url: https://www.cockroachlabs.com
  - name: Operator Source
    url: github.com/cockroachdb/ccapi-k8s-operator
  maintainers:
  - email: support@cockroachlabs.com
    name: Cockroach Labs Support
  maturity: alpha
  provider:
    name: Cockroach Labs
  version: 0.0.1
