# permissions for end users to edit crdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crdbcluster-editor-role
rules:
- apiGroups:
  - ccapi.cockroachdb.cloud
  resources:
  - crdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ccapi.cockroachdb.cloud
  resources:
  - crdbclusters/status
  verbs:
  - get
