# permissions for end users to edit crdbdbaasconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crdbdbaasconnection-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections/status
  verbs:
  - get
