# permissions for end users to view crdbdbaasconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crdbdbaasconnection-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections/status
  verbs:
  - get
