
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ccapi.cockroachdb.cloud
  resources:
  - crdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ccapi.cockroachdb.cloud
  resources:
  - crdbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ccapi.cockroachdb.cloud
  resources:
  - crdbclusters/status
  verbs:
  - get
  - patch
  - update
