
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasinventories/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - crdbdbaasinventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviders/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasproviders/status
  verbs:
  - get
  - patch
  - update
