## Append samples you want in your CSV to this file as resources ##
resources:
- dbaas_v1alpha1_crdbdbaasinventory.yaml
- dbaas_v1alpha1_crdbdbaasconnection.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
